#! /bin/bash

readonly IMAGE_NAME="apostila-aceleradora"
readonly PDF_FILE_NAME="apostila-aceleradora.pdf"

docker_build() {
  docker build -t ${IMAGE_NAME} .
}

docker_run() {
  docker run \
    --tty \
    --interactive \
    --volume ${PWD}:/book \
    ${IMAGE_NAME} $@
}

case $1 in
  build)
    docker_build
    ;;
  serve)
    docker_run gitbook serve
    ;;

  pdf)
    docker_run gitbook pdf . ${PDF_FILE_NAME}
  ;;

  *)
    echo
    echo "Opcao invalida: $1. Tente uma das seguintes:"
    echo -e "\tbuild: Constroi imagem docker"
    echo -e "\tserve: Renderiza apostila no ambiente local (localhost:4000)"
    echo -e "\tpdf: Gera versao PDF da apostila"
  ;;
esac
